import Head from 'next/head';

/* const poppins = Poppins({ subsets: ['latin'], weight: '400' }); */

const Home = () => {
  return (
    <Head>
      <title>Template React | CerradoBit</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Home;
